-- SOCKET Industrial Platform - Supabase Schema v1.6 (Radar & WiFi Sensing)

-- 1. Radar Olayları
CREATE TABLE IF NOT EXISTS public.radar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id TEXT NOT NULL,
    event_type TEXT NOT NULL, -- Hareketsizlik, Düşme, İzinsiz Giriş
    duration_seconds INTEGER DEFAULT 0,
    severity TEXT DEFAULT 'Normal',
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    metadata JSONB DEFAULT '{}'
);

-- RLS
ALTER TABLE public.radar_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Sadece geliştiriciler görebilir" ON public.radar_events;
CREATE POLICY "Sadece geliştiriciler görebilir" ON public.radar_events FOR SELECT USING (true); -- Test için açık, yetki kontrolü frontend'de
