-- SOCKET Industrial Platform - Supabase Schema v1.0

-- 1. Kullanıcı Profilleri (Auth ile bağlı)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE,
    full_name TEXT,
    level TEXT DEFAULT 'Operatör',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Sensör Verileri (Zaman Serisi)
CREATE TABLE IF NOT EXISTS public.sensor_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    metric_id TEXT NOT NULL,
    value FLOAT8 NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- 3. Sistem Logları ve Alarmlar
CREATE TABLE IF NOT EXISTS public.system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    type TEXT NOT NULL, -- INFO, WARNING, ERROR, CRITICAL
    message TEXT NOT NULL,
    source TEXT DEFAULT 'system',
    user_id UUID REFERENCES auth.users(id)
);

-- GÜVENLİK: RLS Ayarları
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;

-- Politikalar: Herkes okuyabilir, sadece yetkililer yazabilir (Basitleştirilmiş)
CREATE POLICY "Herkes profilleri görebilir" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Herkes metrikleri görebilir" ON public.sensor_metrics FOR SELECT USING (true);
CREATE POLICY "Herkes logları görebilir" ON public.system_logs FOR SELECT USING (true);

-- Auth Trigger: Yeni kullanıcı kaydolduğunda otomatik profil oluştur
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, level)
  VALUES (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'level');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
