-- SOCKET Industrial Platform - Supabase Schema v1.5 (Total Integration)

-- 1. Realtime (Canlı Akış) özelliğini tablolar için aktif et
ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_metrics;
ALTER PUBLICATION supabase_realtime ADD TABLE public.system_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.facilities;

-- 2. Yeni Tablolar (Edge Functions / Raporlama Altyapısı)
CREATE TABLE IF NOT EXISTS public.analytics_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL,
    calculated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- RLS
ALTER TABLE public.analytics_cache ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes görebilir" ON public.analytics_cache FOR SELECT USING (true);
