FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Uygulama kodları docker-compose üzerinden volume olarak bağlanacak
ENV PYTHONPATH=/app
CMD ["python", "app/simulator.py"]
